name: Shopee Autoposter

on:
  schedule:
      - cron: "*/3 * * * *"   # every 3 minutes
  workflow_dispatch: # allow manual run from GitHub

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run autoposter
        run: node index.js
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
